<?php

namespace App\Models;

use App\Models\Major;
use App\Models\Traits\HasPublicId;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use App\Services\Image\ImageProcessor;
use Illuminate\Support\Str;

class College extends Model
{
    /** @use HasFactory<\Database\Factories\CollegeFactory> */
    use HasFactory, HasPublicId;

    protected $fillable = [
        'public_id',
        'name',
        'description',
        'image_path',
    ];

    protected $hidden = ['id'];

    public function getRouteKeyName(): string
    {
        return 'public_id';
    }

    public function majors(): HasMany
    {
        return $this->hasMany(Major::class);
    }

    protected static function booted(): void
    {
        static::saved(function (College $model) {
            $original = $model->getOriginal('image_path');
            $current = $model->image_path;

            // if image changed and it's not already a webp generated by our processor
            if ($current && $original !== $current && ! Str::endsWith(strtolower($current), '.webp')) {
                try {
                    $processor = app(ImageProcessor::class);
                    $res = $processor->reprocessFromDisk('public', $current, 'colleges');

                    if (is_array($res) && ! empty($res['path_main'])) {
                        // update model without firing events to avoid recursion
                        static::withoutEvents(function () use ($model, $res) {
                            $model->image_path = $res['path_main'];
                            $model->save();
                        });
                    }
                } catch (\Throwable $e) {
                    report($e);
                }
            }
        });
    }


}
